import { jsPDF } from 'jspdf';
import { Truck, PackedItem, TransformerItem } from '../types';
import { getTruckOriginLabel, getStackingInfo } from './packing';
import { calculateLoadBalance } from './loadBalance';

/**
 * Formats a component description for PDF reports with unit designation ("/1", "/2", etc.)
 * e.g., "HV Bushing /1", "Main Conservator /2", "Radiator Bank A /1 (Rotated 90°)"
 */
export function getComponentDescriptionWithUnit(item: TransformerItem, rotated = false): string {
  let name = item.componentName ? item.componentName.trim() : '';

  // If the name already ends with /<digit>, avoid appending duplicate unit designation
  if (!/\/\s*\d+$/.test(name)) {
    let unitNum = '';

    // 1. Try extracting from projectCode: e.g. "PT0512/1", "PT0512/2", "P101 / 3", "PT0512-2"
    if (item.projectCode) {
      const matchSlash = item.projectCode.match(/\/\s*(?:Unit\s*|U\s*)?(\d+)/i);
      if (matchSlash && matchSlash[1]) {
        unitNum = matchSlash[1];
      } else {
        const matchDash = item.projectCode.match(/[-_]\s*(?:Unit\s*|U\s*)?(\d+)$/i);
        if (matchDash && matchDash[1]) {
          unitNum = matchDash[1];
        }
      }
    }

    // 2. Try extracting from item.id if generated by excel duplicate function (e.g. "box-2-...")
    if (!unitNum && item.id) {
      const matchId = item.id.match(/^box-(\d+)-/);
      if (matchId && matchId[1]) {
        unitNum = matchId[1];
      }
    }

    // 3. Fallback: default to unit 1
    if (!unitNum) {
      unitNum = '1';
    }

    name = `${name} /${unitNum}`;
  }

  if (rotated) {
    name += ' (Rotated 90°)';
  }

  return name;
}

/**
 * Generates a clean, professional PDF report of the Truck Loading Plan
 * Custom layout settings:
 * - Section 1: Summary Dashboard
 * - Section 2: Flat Bed Loading Plan (2 trucks per page)
 * - Section 3: Low Bed / ODC Loading Plan (1 truck per page)
 * - Section 4: Unassigned / Review Required Items (if any)
 */
export function generateLoadingPlanPDF(
  trucks: Truck[],
  unpackedItems: TransformerItem[],
  totalWeight: number,
  globalEfficiency: number,
  payloadCapacity: number,
  exportMode: 'flatbed' | 'lowbed' | 'complete' = 'complete',
  aiInsights: any[] = []
): jsPDF {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  let pageNum = 1;

  // Header and Footer draw utility
  const drawPageHeader = (title: string, pNum: number) => {
    // Dark professional header banner
    doc.setFillColor(15, 23, 42); // Primary Deep Slate
    doc.rect(0, 0, pageWidth, 25, 'F');

    // Voltamp orange/amber highlighting line
    doc.setFillColor(249, 115, 22); // Amber Accent
    doc.rect(0, 25, pageWidth, 1.5, 'F');

    // Left side of the header: company name bold, professional and vertically centered
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(255, 255, 255);
    doc.text('VOLTAMP POWER TRANSFORMERS', 15, 14.5);

    // Right-aligned branding metadata
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.text('Transformer Truck Loading Plan', pageWidth - 15, 8.5, { align: 'right' });

    // Dynamic active Project Codes
    const activeProjects = Array.from(new Set(targetTrucks.flatMap(t => t.items.map(pi => pi.item.projectCode)))).filter(Boolean);
    const projectText = activeProjects.length > 0 ? `${activeProjects.join(', ')}` : 'MULTI-SYSTEM';
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(203, 213, 225);
    doc.text(`Project Code: ${projectText}`.substring(0, 48), pageWidth - 15, 13, { align: 'right' });

    // Report Date
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(148, 163, 184);
    doc.text(`Report Date: ${new Date().toLocaleDateString()}`, pageWidth - 15, 17.5, { align: 'right' });

    // Section title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(249, 115, 22); // Amber highlighted segment title
    doc.text(title.toUpperCase(), pageWidth - 15, 22.5, { align: 'right' });
    
    // Page footer bottom
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(15, pageHeight - 15, pageWidth - 15, pageHeight - 15);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated on: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}  |  Confidential Logistics Report`, 15, pageHeight - 10);
    doc.text(`Page ${pNum}`, pageWidth - 15, pageHeight - 10, { align: 'right' });
  };

  // Filter trucks based on the requested export mode
  const targetTrucks = trucks.filter(t => {
    if (exportMode === 'flatbed') return t.type !== 'Low Bed';
    if (exportMode === 'lowbed') return t.type === 'Low Bed';
    return true; // Complete / Coordinated plan
  });

  // Calculate stats specifically for the target trucks in this PDF
  const totalTrucksCount = targetTrucks.length;
  const omanTrucksCount = targetTrucks.filter(t => t.originGroup === 'Oman').length;
  const importedTrucksCount = targetTrucks.filter(t => t.originGroup === 'Imported').length;
  const lowBedTrucksCount = targetTrucks.filter(t => t.type === 'Low Bed').length;
  const flatBedCount = targetTrucks.filter(t => t.type !== 'Low Bed').length;
  const nonLowBedTypeName = targetTrucks.find(t => t.type !== 'Low Bed')?.type || 'Flat Bed';
  
  const selectedTotalWeight = targetTrucks.reduce((sum, t) => sum + t.items.reduce((sum, pi) => sum + pi.item.weight, 0), 0);
  
  // Calculate specific floor efficiency for selected trucks
  let selectedAvgEfficiency = 0;
  if (targetTrucks.length > 0) {
    const totalOccupancy = targetTrucks.reduce((sum, t) => {
      const usedArea = t.items.reduce((aSum, pi) => aSum + (pi.w * pi.l), 0);
      const totalArea = t.lengthLimit * t.widthLimit;
      return sum + (usedArea / totalArea);
    }, 0);
    selectedAvgEfficiency = (totalOccupancy / targetTrucks.length) * 100;
  }

  // ================= SECTION 1: SUMMARY DASHBOARD =================
  drawPageHeader(`SECTION 1: LOGISTICS REGISTER (${exportMode.toUpperCase()})`, pageNum);

  let currentY = 38;

  // Title block
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  if (exportMode === 'flatbed') {
    doc.text(`${nonLowBedTypeName.toUpperCase()} DISPATCH LOADING REGISTER`, 15, currentY);
  } else if (exportMode === 'lowbed') {
    doc.text('LOW BED / ODC HEAVY ESCORT ROUTE REGISTER', 15, currentY);
  } else {
    doc.text('COMPLETE MULTI-CARRIER CLEARANCE PLAN', 15, currentY);
  }
  currentY += 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text('Standard multi-attribute clearance & dimensional verification statement for transport authorization.', 15, currentY);
  currentY += 10;

  // Stats cards rendering helper
  const drawStatCard = (x: number, y: number, w: number, h: number, title: string, val: string, subText: string, color: [number, number, number]) => {
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(x, y, w, h, 1.5, 1.5, 'F');
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.35);
    doc.roundedRect(x, y, w, h, 1.5, 1.5, 'S');

    doc.setFillColor(color[0], color[1], color[2]);
    doc.rect(x, y, 2.5, h, 'F'); // left accent border

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(100, 116, 139);
    doc.text(title.toUpperCase(), x + 6, y + 6);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(15, 23, 42);
    doc.text(val, x + 6, y + 14);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(148, 163, 184);
    doc.text(subText, x + 6, y + 20);
  };

  const cardW = 55;
  const cardH = 24;

  const carrierSubText = lowBedTrucksCount === 0
    ? `${flatBedCount} ${nonLowBedTypeName} (Flat Bed Only)`
    : flatBedCount === 0
    ? `${lowBedTrucksCount} Low Bed (Low Bed Only)`
    : `${flatBedCount} ${nonLowBedTypeName === 'Flat Bed' ? 'Flatb.' : 'Cont.'} | ${lowBedTrucksCount} Lowb.`;

  // Row 1 cards
  drawStatCard(15, currentY, cardW, cardH, 'Required Rig Carriers', `${totalTrucksCount} Trucks`, carrierSubText, [14, 165, 233]);
  drawStatCard(15 + cardW + 8, currentY, cardW, cardH, 'Cumulative Mass', `${(selectedTotalWeight / 1000).toFixed(2)} Tons`, `${selectedTotalWeight.toLocaleString()} kg total`, [34, 197, 94]);
  drawStatCard(15 + (cardW + 8) * 2, currentY, cardW, cardH, 'Staging Efficiency', `${selectedAvgEfficiency.toFixed(1)}%`, 'Average bed usage', [168, 85, 247]);

  currentY += cardH + 11;

  // Section heading for Allocation Index table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.setTextColor(15, 23, 42);
  doc.text('STAGING FLEET DESPATCH ALLOCATION INDEX', 15, currentY);
  currentY += 5;

  // Allocation table headers
  const colWidths = [20, 30, 45, 20, 25, 20, 20];
  const tableHeaders = ['TRUCK ID', 'TRUCK TYPE', 'CARGO ORIGIN', 'LOAD COUNT', 'TOTAL WEIGHT', 'BED USED %', 'BG SPACE %'];
  
  doc.setFillColor(71, 85, 105);
  doc.rect(15, currentY, pageWidth - 30, 6, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  let curTableX = 15;
  for (let colIdx = 0; colIdx < tableHeaders.length; colIdx++) {
    doc.text(tableHeaders[colIdx], curTableX + 2, currentY + 4.2);
    curTableX += colWidths[colIdx];
  }
  currentY += 6;

  // Draw table contents rows
  if (targetTrucks.length === 0) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('No active truck configurations matching this criteria found.', 20, currentY + 6);
    currentY += 12;
  } else {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(15, 23, 42);

    for (let tIdx = 0; tIdx < targetTrucks.length; tIdx++) {
      const truck = targetTrucks[tIdx];
      curTableX = 15;

      const originText = getTruckOriginLabel(truck);
      const wrappedOrigin = doc.splitTextToSize(originText, colWidths[2] - 4);
      const lineCount = wrappedOrigin.length;
      const rowHeight = Math.max(5.5, lineCount * 2.8 + 1.2);

      // zebra striping
      if (tIdx % 2 === 1) {
        doc.setFillColor(248, 250, 252);
        doc.rect(15, currentY, pageWidth - 30, rowHeight, 'F');
      }

      doc.setDrawColor(226, 232, 240);
      doc.setLineWidth(0.15);
      doc.line(15, currentY + rowHeight, pageWidth - 15, currentY + rowHeight);

      const tWt = truck.items.reduce((sum, pi) => sum + pi.item.weight, 0);
      const uAreaSqM = truck.items.reduce((sum, pi) => sum + (pi.w * pi.l), 0) / 1000000;
      const tAreaSqM = (truck.lengthLimit * truck.widthLimit) / 1000000;
      const usedPercent = Math.min(100, (uAreaSqM / tAreaSqM) * 100);
      const remPercent = 100 - usedPercent;

      const isLowBed = truck.type === 'Low Bed';
      const isContainer = truck.type === '40ft HC Container';
      const rowValues = [
        isLowBed ? `LB#${truck.truckNumber}` : (isContainer ? `HC#${truck.truckNumber}` : `FB#${truck.truckNumber}`),
        isLowBed ? 'Low Bed (Heavy)' : (isContainer ? '40ft HC Container' : 'Flat Bed Logistic'),
        '', // Rendered via wrappedOrigin logic
        `${truck.items.length} pcs`,
        `${tWt.toLocaleString()} kg`,
        `${usedPercent.toFixed(1)}%`,
        `${remPercent.toFixed(1)}%`
      ];

      for (let cIdx = 0; cIdx < rowValues.length; cIdx++) {
        if (cIdx === 2) {
          // Centered line wrapping for Cargo Origin
          const textHeight = lineCount * 2.8 - 0.8;
          const yStart = currentY + (rowHeight - textHeight) / 2 + 1.9;
          for (let l = 0; l < lineCount; l++) {
            doc.text(wrappedOrigin[l], curTableX + 2, yStart + l * 2.8);
          }
        } else {
          // Single-line vertical centering
          const verticalAdjustment = (rowHeight - 5.5) / 2;
          doc.text(rowValues[cIdx], curTableX + 2, currentY + 3.7 + verticalAdjustment);
        }
        curTableX += colWidths[cIdx];
      }
      currentY += rowHeight;

      if (currentY > pageHeight - 45) {
        // Table safety break
        break;
      }
    }
  }

  // Draw unpacked/quarantined accessories warning at the bottom
  const eligibleUnpacked = exportMode === 'lowbed' ? [] : unpackedItems;
  if (eligibleUnpacked.length > 0) {
    currentY += 6;
    doc.setFillColor(254, 242, 242); // deep warn red
    doc.roundedRect(15, currentY, pageWidth - 30, 16, 1, 1, 'F');
    doc.setDrawColor(248, 113, 113);
    doc.setLineWidth(0.4);
    doc.roundedRect(15, currentY, pageWidth - 30, 16, 1, 1, 'S');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(153, 27, 27);
    doc.text('ATTENTION: ACCESSORY SHIFT DETECTED - QUARANTINE ITEMS REQUIRED REVIEW', 18, currentY + 4.5);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(185, 28, 28);
    const itemListStr = eligibleUnpacked.map(item => `${getComponentDescriptionWithUnit(item)} (${item.length}x${item.width})`).join(', ');
    const displayStr = `The following ${eligibleUnpacked.length} components exceed standard ${nonLowBedTypeName.toLowerCase()} dimensional layouts even when rotated: ` + itemListStr;
    doc.text(displayStr.substring(0, 125) + (displayStr.length > 125 ? '...' : ''), 18, currentY + 9);
    doc.text('Go to Section 4 on the last page of the complete report to review details.', 18, currentY + 13);
  }


  // ================= SECTION 2: FLAT BED TRUCKS LOADING PLANS (1 per page) =================
  if (exportMode === 'complete' || exportMode === 'flatbed') {
    const flatBedTrucksList = targetTrucks.filter(t => t.type !== 'Low Bed');
    
    for (let tIdx = 0; tIdx < flatBedTrucksList.length; tIdx++) {
      doc.addPage();
      pageNum++;
      
      const truck = flatBedTrucksList[tIdx];
      drawPageHeader(`SECTION 2: ${truck.type.toUpperCase()} LOADING PLAN`, pageNum);
      drawTruckPageContent(doc, truck, aiInsights);
    }
  }


  // ================= SECTION 3: LOW BED / ODC PLANS (1 per page) =================
  if (exportMode === 'complete' || exportMode === 'lowbed') {
    const lowBedTrucksList = targetTrucks.filter(t => t.type === 'Low Bed');

    for (let lIdx = 0; lIdx < lowBedTrucksList.length; lIdx++) {
      doc.addPage();
      pageNum++;

      const truck = lowBedTrucksList[lIdx];
      drawPageHeader('SECTION 3: HEAVY LOW-BED / ODC STAGING', pageNum);
      drawTruckPageContent(doc, truck, aiInsights);
    }
  }


  // ================= SECTION 4: UNASSIGNED ACCESSORIES REVIEW =================
  if ((exportMode === 'complete' || exportMode === 'flatbed') && unpackedItems.length > 0) {
    doc.addPage();
    pageNum++;
    drawPageHeader('SECTION 4: UNRESOLVED / REVIEW NEEDED', pageNum);

    let curY = 32;

    doc.setFillColor(254, 242, 242); // bold dark quarantine background
    doc.roundedRect(15, curY, pageWidth - 30, 18, 1, 1, 'F');
    doc.setDrawColor(239, 68, 68);
    doc.setLineWidth(0.4);
    doc.roundedRect(15, curY, pageWidth - 30, 18, 1, 1, 'S');

    doc.setTextColor(153, 27, 27);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text('UNASSIGNED ACCESSORIES UNDER LOGISTICS DISCREPANCY HOLD', 19, curY + 6);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(185, 28, 28);
    doc.text(`The components registered below exceed default 2D ${nonLowBedTypeName} clear space dimensions.`, 19, curY + 11.5);
    doc.text(`Manual dispatch review, custom ${nonLowBedTypeName.toLowerCase()} setups or dedicated separate small rigs are required for clearance.`, 19, curY + 15);

    curY += 23;

    // Table listing
    const unassignedColWidths = [15, 30, 65, 35, 20, 15];
    const unassignedHeaders = ['ITEM IND', 'PART CODE', 'COMPONENT DESCRIPTION', 'DIMENSIONS (L x W x H) mm', 'WEIGHT', 'ORIGIN'];

    doc.setFillColor(51, 65, 85);
    doc.rect(15, curY, pageWidth - 30, 5, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    let uX = 15;
    for (let c = 0; c < unassignedHeaders.length; c++) {
      doc.text(unassignedHeaders[c], uX + 2, curY + 3.8);
      uX += unassignedColWidths[c];
    }
    curY += 5;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(15, 23, 42);

    for (let uIdx = 0; uIdx < unpackedItems.length; uIdx++) {
      const item = unpackedItems[uIdx];
      uX = 15;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      const wrappedName = doc.splitTextToSize(getComponentDescriptionWithUnit(item), unassignedColWidths[2] - 4);
      const wrappedProjectCode = doc.splitTextToSize(item.projectCode || '', unassignedColWidths[1] - 4);
      const maxLineCount = Math.max(wrappedName.length, wrappedProjectCode.length);
      const rowHeight = Math.max(4.5, maxLineCount * 2.5 + 1.2);

      if (uIdx % 2 === 1) {
        doc.setFillColor(248, 250, 252);
        doc.rect(15, curY, pageWidth - 30, rowHeight, 'F');
      }

      doc.setDrawColor(226, 232, 240);
      doc.setLineWidth(0.1);
      doc.line(15, curY + rowHeight, pageWidth - 15, curY + rowHeight);

      const cells = [
        `UN-#${uIdx + 1}`,
        '', // Handled below
        '', // Handled below
        `${item.length}×${item.width}×${item.height} mm`,
        `${item.weight.toLocaleString()} kg`,
        item.origin
      ];

      for (let c = 0; c < cells.length; c++) {
        if (c === 1) {
          for (let l = 0; l < wrappedProjectCode.length; l++) {
            doc.text(wrappedProjectCode[l], uX + 2, curY + 3.2 + (l * 2.5));
          }
        } else if (c === 2) {
          for (let l = 0; l < wrappedName.length; l++) {
            doc.text(wrappedName[l], uX + 2, curY + 3.2 + (l * 2.5));
          }
        } else {
          const verticalAdjustment = (rowHeight - 4.5) / 2;
          doc.text(cells[c], uX + 2, curY + 3.2 + verticalAdjustment);
        }
        uX += unassignedColWidths[c];
      }
      curY += rowHeight;

      if (curY > pageHeight - 30) break;
    }
  }



  return doc;
}

/**
 * Draws a single flatbed or lowbed truck layout, statistics, and detailed components table
 * perfectly formatted on a single A4 Portrait sheet.
 */
/**
 * Draws a single flatbed or lowbed truck layout, statistics, and detailed components table
 * perfectly formatted on a single A4 Portrait sheet.
 */
function drawTruckPageContent(doc: jsPDF, truck: Truck, aiInsights: any[] = []) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  let curY = 32;

  // 1. Truck Subheader
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text(`${truck.type.toUpperCase()} #${truck.truckNumber}`, 15, curY);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(`Origin Segment: ${getTruckOriginLabel(truck).toUpperCase()}`, pageWidth - 15, curY, { align: 'right' });
  
  curY += 6;

  // 2. [Truck Layout Visuals: Side-by-Side 2D Top-Down Blueprint and 3D Isometric Projection]
  const leftColWidth = 74; // slightly shrunk for horizontal breathing room
  const rightColWidth = 90; // expanded to give more presence to 3D projection
  const colGap = 16; // space between columns
  
  const pL = truck.physicalLength || (truck.type === 'Low Bed' ? 14000 : 12000);
  const physicalW = truck.physicalWidth || 2400;
  const physicalH = truck.physicalHeight || 2500;
  
  // Center physical 2D diagram on page
  const bedX = 15;
  const bedY = curY + 14; // Pushed down to clear the header completely
  
  // Scale for 2D visual (fits in leftColWidth)
  const scale2D = leftColWidth / pL;
  const bedW_physical = pL * scale2D;
  const bedH = physicalW * scale2D;   // bed height based on truck width
 
  // Let's draw Left Column: 2D Top-Down Blueprint
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(100, 116, 139);
  doc.text('2D TOP-DOWN BLUEPRINT LAYOUT', bedX, curY + 3); // 11mm of visual clearance below title text

  // Cabin
  doc.setFillColor(148, 163, 184);
  doc.roundedRect(bedX - 6, bedY + (bedH / 10), 4.5, bedH * 0.8, 0.8, 0.8, 'F');
  doc.setFillColor(203, 213, 225);
  doc.rect(bedX - 3, bedY + (bedH * 0.2), 1.8, bedH * 0.6, 'F');

  // Truck Bed border
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(30, 41, 59);
  doc.setLineWidth(0.35);
  doc.rect(bedX, bedY, bedW_physical, bedH, 'FD');

  // Grid interior lines over full physical bed
  doc.setDrawColor(241, 245, 249);
  doc.setLineWidth(0.08);
  for (let gridIdx = 1; gridIdx <= 3; gridIdx++) {
    const gy = bedY + (bedH / 4) * gridIdx;
    doc.line(bedX, gy, bedX + bedW_physical, gy);
  }
  const gridStepScaled = 2000 * scale2D;
  for (let gx = bedX + gridStepScaled; gx < bedX + bedW_physical; gx += gridStepScaled) {
    doc.line(gx, bedY, gx, bedY + bedH);
  }

  // Calculate actual used packing length & clearance
  const actualUsedLength = truck.items.length > 0 ? Math.max(...truck.items.map(pi => pi.x + pi.w)) : 0;
  const bedClearance = pL - actualUsedLength;

  // GREEN SAFETY AREA: soft semi-transparent green represent safe clear space
  if (bedClearance > 0) {
    const rectX = bedX + (actualUsedLength * scale2D);
    const rectY = bedY;
    const rectW = bedW_physical - (actualUsedLength * scale2D);
    const rectH = bedH;

    doc.setFillColor(240, 253, 244); // Emerald-50 background
    doc.rect(rectX, rectY, rectW, rectH, 'F');

    // Soft green hatch lines
    if (rectW > 0.1) {
      doc.setDrawColor(134, 239, 172); // Emerald-300 lines
      doc.setLineWidth(0.12);
      const spacing = 2.0;
      for (let c = rectX - rectH; c < rectX + rectW; c += spacing) {
        const pts: { x: number; y: number }[] = [];
        const xTop = c + rectY;
        if (xTop >= rectX && xTop <= rectX + rectW) pts.push({ x: xTop, y: rectY });
        const xBottom = c + rectY + rectH;
        if (xBottom >= rectX && xBottom <= rectX + rectW) pts.push({ x: xBottom, y: rectY + rectH });
        const yLeft = rectX - c;
        if (yLeft >= rectY && yLeft <= rectY + rectH) pts.push({ x: rectX, y: yLeft });
        const yRight = rectX + rectW - c;
        if (yRight >= rectY && yRight <= rectY + rectH) pts.push({ x: rectX + rectW, y: yRight });

        const uniquePts: { x: number; y: number }[] = [];
        for (const p of pts) {
          if (!uniquePts.some(up => Math.abs(up.x - p.x) < 0.01 && Math.abs(up.y - p.y) < 0.01)) {
            uniquePts.push(p);
          }
        }
        if (uniquePts.length === 2) {
          doc.line(uniquePts[0].x, uniquePts[0].y, uniquePts[1].x, uniquePts[1].y);
        }
      }
    }

    // Green separator line
    doc.setDrawColor(22, 163, 74); // Green-600
    doc.setLineWidth(0.4);
    if (typeof (doc as any).setLineDashPattern === 'function') {
      (doc as any).setLineDashPattern([1.2, 0.8], 0);
    } else if (typeof (doc as any).setLineDash === 'function') {
      (doc as any).setLineDash([1.2, 0.8], 0);
    }
    doc.line(rectX, rectY, rectX, rectY + rectH);

    // Reset line dash
    if (typeof (doc as any).setLineDashPattern === 'function') {
      (doc as any).setLineDashPattern([], 0);
    } else if (typeof (doc as any).setLineDash === 'function') {
      (doc as any).setLineDash([], 0);
    }

    // Exterior text label stacked vertically inside the middle gap
    if (rectW > 0.1) {
      const labelX = bedX + bedW_physical + 3.5;
      const centerY = rectY + rectH / 2;

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(6.5);
      doc.setTextColor(30, 41, 59); // deep slate grey

      const lh = 2.6; // line height
      doc.text("NET RESERVED", labelX, centerY - lh, { align: 'left', baseline: 'middle' });
      doc.text("CLEARANCE:", labelX, centerY, { align: 'left', baseline: 'middle' });
      doc.text(`${bedClearance} mm`, labelX, centerY + lh, { align: 'left', baseline: 'middle' });

      // Small clean indicator arrow pointing left back into safety zone
      const arrowStartX = labelX - 1.2;
      const arrowEndX = rectX + rectW / 2;
      if (arrowStartX > arrowEndX + 1) {
        doc.setDrawColor(100, 116, 139);
        doc.setLineWidth(0.2);
        doc.line(arrowStartX, centerY, arrowEndX, centerY);
        doc.line(arrowEndX, centerY, arrowEndX + 0.8, centerY - 0.6);
        doc.line(arrowEndX, centerY, arrowEndX + 0.8, centerY + 0.6);
      }
    }
  }

  // Draw 2D components layer
  const diagramStacking = getStackingInfo(truck.items);
  const diagramRenderItems = truck.items.map((pi, originalIndex) => {
    const sInfo = diagramStacking[pi.item.id];
    const layer = sInfo ? sInfo.layer : 1;
    const loadedOnId = sInfo ? sInfo.loadedOnId : null;
    return {
      pi,
      originalIndex,
      layer,
      loadedOnId
    };
  });

  const sorted2DItems = [...diagramRenderItems].sort((a, b) => a.layer - b.layer);

  for (let rIdx = 0; rIdx < sorted2DItems.length; rIdx++) {
    const { pi, originalIndex, layer, loadedOnId } = sorted2DItems[rIdx];
    
    // Stacking visual offset in 2D
    const offset = (layer - 1) * 1.0;
    const ix = bedX + pi.x * scale2D + offset;
    const iy = bedY + pi.y * scale2D + offset;
    const iw = pi.w * scale2D;
    const il = pi.l * scale2D;

    const isOman = pi.item.origin.toLowerCase().trim() === 'oman';
    const isBottomWithStacked = layer === 1 && sorted2DItems.some(item => item.loadedOnId === pi.item.id);

    if (isBottomWithStacked) {
      doc.setFillColor(248, 250, 252);
      doc.setDrawColor(148, 163, 184);
    } else if (isOman) {
      doc.setFillColor(254, 215, 170); // soft orange
      doc.setDrawColor(249, 115, 22);
    } else {
      doc.setFillColor(207, 250, 254); // soft cyan
      doc.setDrawColor(14, 165, 233);
    }

    doc.setLineWidth(0.25);

    if (isBottomWithStacked) {
      if (typeof (doc as any).setLineDashPattern === 'function') {
        (doc as any).setLineDashPattern([1.0, 0.6], 0);
      } else if (typeof (doc as any).setLineDash === 'function') {
        (doc as any).setLineDash([1.0, 0.6], 0);
      }
    }

    doc.rect(ix, iy, iw, il, 'FD');

    // Reset dash patterns
    if (typeof (doc as any).setLineDashPattern === 'function') {
      (doc as any).setLineDashPattern([], 0);
    } else if (typeof (doc as any).setLineDash === 'function') {
      (doc as any).setLineDash([], 0);
    }

    // Draw center of gravity cross lines if Low Bed
    if (truck.type === 'Low Bed') {
      doc.setDrawColor(239, 68, 68);
      doc.setLineWidth(0.1);
      doc.line(ix, iy, ix + iw, iy + il);
      doc.line(ix, iy + il, ix + iw, iy);
    }

    // Index tag overlay
    if (iw > 2 && il > 2) {
      doc.setTextColor(15, 23, 42);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(5.5);
      
      const topMostBundledItem = sorted2DItems.find(item => item.loadedOnId === pi.item.id && item.layer > 1);
      let label = `#${originalIndex + 1}`;
      
      if (layer === 1 && topMostBundledItem) {
        label = ''; // Hide ground label if covered
      } else if (layer > 1) {
        const underPi = truck.items.find(itemPi => itemPi.item.id === loadedOnId);
        const underNum = underPi ? truck.items.indexOf(underPi) + 1 : null;
        if (underNum) {
          label = `#${originalIndex + 1}/${underNum}`;
        }
      }

      if (label) {
        doc.text(label, ix + (iw / 2), iy + (il / 2) + 1.8, { align: 'center' });
      }
    }
  }

  // --- RIGHT COLUMN: 3D ISOMETRIC VIEW GRAPHIC ---
  const rightColXStart = bedX + leftColWidth + colGap;
  const centerX = rightColXStart + rightColWidth / 2;   // centered in right column

  // Title for Right Visual
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(100, 116, 139);
  doc.text('3D ISOMETRIC PROJECTION GUIDE', rightColXStart, curY + 3); // perfectly level with 2D title at curY + 3

  const cos30 = 0.866;
  const sin30 = 0.5;

  // Base scale factor is increased by ~45% (from 52 to 75) for a robust, thick 3D isometric representation
  const baseScaleFactor = 75;
  
  // Calculate vertical center of the 2D blueprint to align the 3D projection with it
  const centerY_2D = bedY + bedH / 2;
  
  // Define strict top and bottom limits to prevent any overlap
  const Y_top_limit = curY + 3.5; // Strict top limit to never touch the subheader (32) or titles (curY+3)
  const Y_bottom_limit = (bedY + bedH + 18) - 1.5; // Expanded bottom budget to accommodate the larger 3D model
  
  // H_unit represents the height of the projected truck box per unit of scaleFactor:
  // H_proj = scaleFactor * H_unit
  const H_unit = (0.5 + physicalH / (pL + physicalW)) / cos30;
  
  // To center H_proj vertically around centerY_2D, the height of H_proj must not exceed:
  const H_proj_max = 2 * Math.min(centerY_2D - Y_top_limit, Y_bottom_limit - centerY_2D);
  const scaleFactor_max = H_proj_max / H_unit;
  
  // Determine final scale factor, capped to prevent overlaps on ultra-tall or ultra-long setups
  const finalScaleFactor = Math.min(baseScaleFactor, scaleFactor_max);
  const isoScale = finalScaleFactor / ((pL + physicalW) * cos30);
  
  // Perfectly center the 3D projection vertically relative to the 2D layout
  const centerY_3D = centerY_2D + 0.5 * physicalH * isoScale;

  const projectIso = (x: number, y: number, z: number) => {
    // Center translation relative to truck bed center point
    const dx = x - pL / 2;
    const dy = y - physicalW / 2;
    const rx = (dx * cos30 - dy * cos30) * isoScale;
    const ry = ((dx * sin30 + dy * sin30) - z) * isoScale;
    return {
      x: centerX + rx,
      y: centerY_3D + ry
    };
  };

  const drawFilledQuad = (
    p1: { x: number; y: number },
    p2: { x: number; y: number },
    p3: { x: number; y: number },
    p4: { x: number; y: number },
    fillColor: [number, number, number],
    drawOutline = true
  ) => {
    doc.setFillColor(fillColor[0], fillColor[1], fillColor[2]);
    doc.triangle(p1.x, p1.y, p2.x, p2.y, p3.x, p3.y, 'F');
    doc.triangle(p1.x, p1.y, p3.x, p3.y, p4.x, p4.y, 'F');
    if (drawOutline) {
      doc.setDrawColor(47, 55, 69); // clean tech outline
      doc.setLineWidth(0.12);
      doc.line(p1.x, p1.y, p2.x, p2.y);
      doc.line(p2.x, p2.y, p3.x, p3.y);
      doc.line(p3.x, p3.y, p4.x, p4.y);
      doc.line(p4.x, p4.y, p1.x, p1.y);
    }
  };

  // Determine if vehicle is a container
  const isContainer = truck.type.toLowerCase().includes('container');

  // 1. Calculate the 8 volumetric corner coordinates for the complete container wireframe/bounding box
  const cb1 = projectIso(0, 0, 0); // back-most bottom corner
  const cb2 = projectIso(pL, 0, 0); // bottom right
  const cb3 = projectIso(pL, physicalW, 0); // front-most bottom corner
  const cb4 = projectIso(0, physicalW, 0); // bottom left

  const ct1 = projectIso(0, 0, physicalH); // back-most top corner
  const ct2 = projectIso(pL, 0, physicalH); // top right
  const ct3 = projectIso(pL, physicalW, physicalH); // front-most top corner
  const ct4 = projectIso(0, physicalW, physicalH); // top left

  // 2. Draw ground floor plate first
  drawFilledQuad(cb1, cb2, cb3, cb4, [248, 250, 252], false);

  // 3. Draw background wireframe (rear/far sides of bounding box that reside behind cargo)
  doc.setDrawColor(203, 213, 225); // Slate-200
  doc.setLineWidth(0.12);
  doc.line(cb1.x, cb1.y, cb2.x, cb2.y);
  doc.line(cb1.x, cb1.y, cb4.x, cb4.y);
  if (isContainer) {
    doc.line(cb1.x, cb1.y, ct1.x, ct1.y);
  }

  // 4. Draw floor grid lines inside the container floor boundaries
  doc.setDrawColor(241, 245, 249);
  doc.setLineWidth(0.08);
  for (let gy = 0; gy <= physicalW; gy += 600) {
    const start = projectIso(0, gy, 0);
    const end = projectIso(pL, gy, 0);
    doc.line(start.x, start.y, end.x, end.y);
  }
  for (let gx = 0; gx <= pL; gx += 2000) {
    const start = projectIso(gx, 0, 0);
    const end = projectIso(gx, physicalW, 0);
    doc.line(start.x, start.y, end.x, end.y);
  }

  // 5. Draw dynamic "NET RESERVED CLEARANCE" light green highlight in 3D
  if (bedClearance > 0) {
    // Starts immediately at actualUsedLength and extends to the very tail (pL)
    const sp1 = projectIso(actualUsedLength, 0, 0);
    const sp2 = projectIso(pL, 0, 0);
    const sp3 = projectIso(pL, physicalW, 0);
    const sp4 = projectIso(actualUsedLength, physicalW, 0);

    // Light green solid background
    drawFilledQuad(sp1, sp2, sp3, sp4, [240, 253, 244], false);

    // Draw dynamic green hatch/grid pattern in 3D (Emerald-200)
    doc.setDrawColor(187, 247, 208);
    doc.setLineWidth(0.08);
    const hatchSpacing = 400;
    for (let gx = actualUsedLength + hatchSpacing; gx < pL; gx += hatchSpacing) {
      const hStart = projectIso(gx, 0, 0);
      const hEnd = projectIso(gx, physicalW, 0);
      doc.line(hStart.x, hStart.y, hEnd.x, hEnd.y);
    }

    // Bold Green border defining the clearance envelope (Green-600)
    doc.setDrawColor(22, 163, 74);
    doc.setLineWidth(0.25);
    doc.line(sp1.x, sp1.y, sp2.x, sp2.y);
    doc.line(sp2.x, sp2.y, sp3.x, sp3.y);
    doc.line(sp3.x, sp3.y, sp4.x, sp4.y);
    doc.line(sp4.x, sp4.y, sp1.x, sp1.y);
  }

  // 6. Draw 3D Components Layer
  const sorted3DItems = [...diagramRenderItems].sort((a, b) => {
    const sumA = a.pi.x + a.pi.y;
    const sumB = b.pi.x + b.pi.y;
    if (Math.abs(sumA - sumB) > 0.1) {
      return sumA - sumB;
    }
    return a.layer - b.layer;
  });

  for (let rIdx = 0; rIdx < sorted3DItems.length; rIdx++) {
    const { pi, originalIndex, layer, loadedOnId } = sorted3DItems[rIdx];

    const underPi = truck.items.find(item => item.item.id === loadedOnId);
    const zBase = underPi ? underPi.item.height : 0;
    const zTop = zBase + pi.item.height;

    const x0 = pi.x;
    const x1 = pi.x + pi.w;
    const y0 = pi.y;
    const y1 = pi.y + pi.l;

    const b1 = projectIso(x0, y0, zBase);
    const b2 = projectIso(x1, y0, zBase);
    const b3 = projectIso(x1, y1, zBase);
    const b4 = projectIso(x0, y1, zBase);
    const t1 = projectIso(x0, y0, zTop);
    const t2 = projectIso(x1, y0, zTop);
    const t3 = projectIso(x1, y1, zTop);
    const t4 = projectIso(x0, y1, zTop);

    const isOman = pi.item.origin.toLowerCase().trim() === 'oman';
    const isBottomWithStacked = layer === 1 && sorted3DItems.some(item => item.loadedOnId === pi.item.id);

    let colTop: [number, number, number];
    let colRight: [number, number, number];
    let colLeft: [number, number, number];

    if (isBottomWithStacked) {
      colTop = [241, 245, 249];
      colRight = [203, 213, 225];
      colLeft = [148, 163, 184];
    } else if (isOman) {
      colTop = [254, 215, 170];   // soft amber-100
      colRight = [251, 146, 60];   // amber-400
      colLeft = [234, 88, 12];     // orange-600
    } else {
      colTop = [207, 250, 254];   // soft cyan-100
      colRight = [56, 189, 248];   // cyan-400
      colLeft = [2, 132, 199];     // sky-600
    }

    drawFilledQuad(t1, t2, t3, t4, colTop);       // Top face
    drawFilledQuad(b2, b3, t3, t2, colRight);    // Front-Right face
    drawFilledQuad(b3, b4, t4, t3, colLeft);     // Front-Left face

    if (truck.type === 'Low Bed') {
      doc.setDrawColor(239, 68, 68);
      doc.setLineWidth(0.08);
      doc.line(t1.x, t1.y, t3.x, t3.y);
      doc.line(t2.x, t2.y, t4.x, t4.y);
    }

    const tcX = (t1.x + t3.x) / 2;
    const yOffset = 0.8 * (finalScaleFactor / 52);
    const tcY = (t1.y + t3.y) / 2 + yOffset;
    doc.setFont('helvetica', 'bold');
    const labelFontSize = Math.max(3.8, Math.min(5.5, 5.5 * (finalScaleFactor / 52)));
    doc.setFontSize(labelFontSize);
    doc.setTextColor(15, 23, 42);
    doc.text(`#${originalIndex + 1}`, tcX, tcY, { align: 'center' });
  }

  // 7. Draw foreground wireframe (closest corners/edges of bounding box and roof) running on top of cargo
  doc.setDrawColor(148, 163, 184); // Slate-400
  doc.setLineWidth(0.12);

  // Foreground bottom edges
  doc.line(cb2.x, cb2.y, cb3.x, cb3.y);
  doc.line(cb4.x, cb4.y, cb3.x, cb3.y);

  if (isContainer) {
    // 3 foreground vertical corner pillars
    doc.line(cb2.x, cb2.y, ct2.x, ct2.y);
    doc.line(cb3.x, cb3.y, ct3.x, ct3.y);
    doc.line(cb4.x, cb4.y, ct4.x, ct4.y);

    // 4 top roof boundary edges
    doc.line(ct1.x, ct1.y, ct2.x, ct2.y);
    doc.line(ct2.x, ct2.y, ct3.x, ct3.y);
    doc.line(ct3.x, ct3.y, ct4.x, ct4.y);
    doc.line(ct4.x, ct4.y, ct1.x, ct1.y);
  }

  // Visual specifications subtitle
  doc.setTextColor(100, 116, 139);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.5);
  doc.text(`Dimensions: ${pL}×${physicalW}×${physicalH} mm | Used Length: ${actualUsedLength} mm | Tail Clearance: ${bedClearance} mm`, bedX, bedY + bedH + 5);

  curY = bedY + bedH + 18;

  // 3. [Truck Statistics Dashboard Card]
  const tWt = truck.items.reduce((sum, pi) => sum + pi.item.weight, 0);
  const uAreaSqM = truck.items.reduce((sum, pi) => sum + (pi.w * pi.l), 0) / 1000000;
  const tAreaSqM = (truck.lengthLimit * truck.widthLimit) / 1000000;
  const usedPercent = Math.min(100, (uAreaSqM / tAreaSqM) * 100);
  const remPercent = Math.max(0, 100 - usedPercent);
  const balanceResult = calculateLoadBalance(truck);

  const boxH = 13;
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(15, curY, pageWidth - 30, boxH, 1, 1, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.2);
  doc.roundedRect(15, curY, pageWidth - 30, boxH, 1, 1, 'S');

  const colStartX = [15, 56, 88, 119, 154];

  // Col 1: Weight
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(6);
  doc.setTextColor(100, 116, 139);
  doc.text('TOTAL PAYLOAD MASS', colStartX[0] + 3.5, curY + 3.8);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(15, 23, 42);
  doc.text(`${tWt.toLocaleString()} kg / ${truck.weightLimit.toLocaleString()} kg`, colStartX[0] + 3.5, curY + 8.5);

  // Col 2: Bed Utilization
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(6);
  doc.setTextColor(100, 116, 139);
  doc.text('BED UTILIZATION %', colStartX[1] + 3.5, curY + 3.8);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(15, 23, 42);
  doc.text(`${usedPercent.toFixed(1)}% used`, colStartX[1] + 3.5, curY + 8.5);

  // Col 3: Space Available
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(6);
  doc.setTextColor(100, 116, 139);
  doc.text('REMAINING SPACE', colStartX[2] + 3.5, curY + 3.8);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(15, 23, 42);
  doc.text(`${remPercent.toFixed(1)}% free`, colStartX[2] + 3.5, curY + 8.5);

  // Col 4: Items Count
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(6);
  doc.setTextColor(100, 116, 139);
  doc.text('LOAD COUNT', colStartX[3] + 3.5, curY + 3.8);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(15, 23, 42);
  doc.text(`${truck.items.length} component${truck.items.length === 1 ? '' : 's'}`, colStartX[3] + 3.5, curY + 8.5);

  // Col 5: Estimated Load Balance
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(6);
  doc.setTextColor(100, 116, 139);
  doc.text('ESTIMATED LOAD BALANCE', colStartX[4] + 3.5, curY + 3.8);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(15, 23, 42);
  doc.text(`${balanceResult.score}%`, colStartX[4] + 3.5, curY + 8.5);

  // Col dividers
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.15);
  doc.line(56, curY + 2, 56, curY + boxH - 2);
  doc.line(88, curY + 2, 88, curY + boxH - 2);
  doc.line(119, curY + 2, 119, curY + boxH - 2);
  doc.line(154, curY + 2, 154, curY + boxH - 2);

  curY += boxH + 5;

  // 4. [Prone Dynamic Manifest Table with Exact Requested Columns]
  const tableStartY = curY;
  const colWidths = [18, 72, 42, 24, 24]; // 180 total
  const tableHeaders = ['[ITEM #]', '[COMPONENT DESCRIPTION]', '[DIMENSIONS (LxWxH) mm]', '[WEIGHT kg]', '[STACKING LEVEL]'];

  doc.setFillColor(51, 65, 85);
  doc.rect(15, tableStartY, pageWidth - 30, 5, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(6.5);
  let tblX = 15;
  for (let c = 0; c < tableHeaders.length; c++) {
    doc.text(tableHeaders[c], tblX + 2, tableStartY + 3.5);
    tblX += colWidths[c];
  }

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.5);
  doc.setTextColor(15, 23, 42);
  let rowY = tableStartY + 5;

  for (let pIdx = 0; pIdx < truck.items.length; pIdx++) {
    const pi = truck.items[pIdx];
    tblX = 15;

    const rowHeight = 6.0;
    if (rowY + rowHeight > pageHeight - 20) {
      doc.addPage();
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.text(`Generated on: ${new Date().toLocaleDateString()} | Confidential Logistics Report`, 15, pageHeight - 10);
      
      doc.setFillColor(15, 23, 42);
      doc.rect(0, 0, pageWidth, 15, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.text(`MANIFEST INDEX CONTINUED - ${truck.type.toUpperCase()} #${truck.truckNumber}`, 15, 9);
      
      rowY = 22;
      doc.setFillColor(51, 65, 85);
      doc.rect(15, rowY, pageWidth - 30, 4.5, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(6);
      let thX = 15;
      for (let c = 0; c < tableHeaders.length; c++) {
        doc.text(tableHeaders[c], thX + 2, rowY + 3.1);
        thX += colWidths[c];
      }
      rowY += 4.5;
    }

    if (pIdx % 2 === 1) {
      doc.setFillColor(248, 250, 252);
      doc.rect(15, rowY, pageWidth - 30, rowHeight, 'F');
    }

    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.08);
    doc.line(15, rowY + rowHeight, pageWidth - 15, rowY + rowHeight);

    const sInfo = diagramStacking[pi.item.id];
    let stackingText = "Ground";
    if (sInfo && sInfo.layer > 1) {
      const underPi = truck.items.find(itemPi => itemPi.item.id === sInfo.loadedOnId);
      const underNum = underPi ? truck.items.indexOf(underPi) + 1 : '?';
      stackingText = `Level ${sInfo.layer} (Stacked on #${underNum})`;
    } else if (sInfo && sInfo.layer === 1) {
      const hasOnTop = truck.items.some(itemPi => {
        const otherSInfo = diagramStacking[itemPi.item.id];
        return otherSInfo && otherSInfo.loadedOnId === pi.item.id && otherSInfo.layer > 1;
      });
      if (hasOnTop) {
        stackingText = "Ground (Covered)";
      }
    }

    const descName = getComponentDescriptionWithUnit(pi.item, pi.rotated);
    const wrappedDesc = doc.splitTextToSize(descName, colWidths[1] - 4);

    const cells = [
      `#${pIdx + 1}`,
      wrappedDesc[0],
      `${pi.item.length} × ${pi.item.width} × ${pi.item.height} mm`,
      `${pi.item.weight.toLocaleString()} kg`,
      stackingText
    ];

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.5);
    doc.setTextColor(15, 23, 42);

    for (let c = 0; c < cells.length; c++) {
      doc.text(cells[c], tblX + 2, rowY + 3.8);
      tblX += colWidths[c];
    }
    rowY += rowHeight;
  }

  // 5. "AI LOADING EXPERT ANALYSIS" SUMMARY BLOCK
  const totalItemWt = truck.items.reduce((sum, pi) => sum + pi.item.weight, 0);
  const cogX = truck.items.length > 0 
    ? truck.items.reduce((sum, pi) => sum + (pi.x + pi.w / 2) * pi.item.weight, 0) / totalItemWt
    : 0;
  
  const cogX_percent = pL > 0 ? (cogX / pL * 100) : 0;

  // Compile Dynamic Bullets based on metrics
  const bullets: { key: string; text: string }[] = [];

  // A. COG SKEW DETECTION
  let cogTextEn = "";
  if (truck.items.length === 0) {
    cogTextEn = "No cargo loaded. Center of Gravity rests exactly at neutral chassis floor centerline.";
  } else if (cogX_percent >= 40 && cogX_percent <= 50) {
    cogTextEn = "Excellent longitudinal equilibrium.";
  } else {
    cogTextEn = "Asymmetrical load distribution detected. Ensure heavy items are chained tightly against forward chassis shifting.";
  }
  bullets.push({ key: '• CENTER OF GRAVITY (CoG) ALIGNMENT:', text: cogTextEn });

  // B. UTILIZATION-BASED PHRASING
  let utilizationTextEn = "";
  if (usedPercent < 30) {
    utilizationTextEn = "FLEET INEFFICIENCY WARNING: This container is severely under-utilized. Recommend migrating these few components into other convoy trucks and eliminating this vehicle to save transit costs.";
  } else if (usedPercent <= 75) {
    utilizationTextEn = "OPTIMAL & SECURE. Standard commercial load profile with balanced spacing and ideal structural margins.";
  } else {
    utilizationTextEn = "HEAVY LOAD ALERT: High-capacity load profile. Fleet manager must instruct the driver regarding extended braking distances and mandatory tire pressure monitoring during transit.";
  }
  bullets.push({ key: '• VEHICLE CAPACITY UTILIZATION:', text: utilizationTextEn });

  // C. CARGO-SPECIFIC RISK INJECTION
  const hasLiquidCargo = truck.items.some(pi => {
    const name = (pi.item.componentName || "").toUpperCase();
    const packing = (pi.item.typeOfPacking || "").toUpperCase();
    return name.includes("BARREL") || name.includes("OIL") || packing.includes("BARREL") || packing.includes("OIL");
  });

  if (hasLiquidCargo) {
    bullets.push({
      key: '• LIQUID CARGO HAZARD WARNING:',
      text: "LIQUID CARGO HAZARD: Loose fluid containers detected. Strict cross-tie tie-down constraints are mandatory to mitigate fluid sloshing during sudden cornering."
    });
  }

  // D. NET RESERVED CLEARANCE
  const clearanceTextEn = `STABLE rear buffer. A clearance zone of ${bedClearance} mm is secured at the cargo bed tail, preventing overhang hazards and ensuring standard transit safety rules.`;
  bullets.push({ key: '• NET RESERVED CLEARANCE (REAR):', text: clearanceTextEn });

  // Pre-calculate wrapped text lines and card height
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6);
  
  const bulletStartYOffset = 11.5;
  const bottomPadding = 3.5;
  const colGapSpacing = 1.6;
  
  const wrappedBullets = bullets.map(b => {
    const wrapped = doc.splitTextToSize(b.text, 130);
    // Estimated line height is 2.6mm for 6pt font, with some padding
    const bulletHeight = (wrapped.length * 2.6) + 1.2;
    return {
      key: b.key,
      wrapped: wrapped,
      height: bulletHeight
    };
  });

  let computedBulletsHeight = 0;
  for (let i = 0; i < wrappedBullets.length; i++) {
    computedBulletsHeight += wrappedBullets[i].height;
    if (i < wrappedBullets.length - 1) {
      computedBulletsHeight += colGapSpacing;
    }
  }

  const aiSectionHeight = Math.max(36, bulletStartYOffset + computedBulletsHeight + bottomPadding);

  if (rowY + aiSectionHeight > pageHeight - 18) {
    doc.addPage();
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, pageWidth, 15, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.text(`AI TECHNICAL AUDIT SUMMARY - ${truck.type.toUpperCase()} #${truck.truckNumber}`, 15, 9);
    rowY = 22;
  } else {
    rowY += 4;
  }

  doc.setFillColor(248, 250, 252); // slate-50
  doc.rect(15, rowY, pageWidth - 30, aiSectionHeight, 'F');
  doc.setDrawColor(226, 232, 240); // slate-200 border
  doc.setLineWidth(0.3);
  doc.rect(15, rowY, pageWidth - 30, aiSectionHeight, 'S');

  // Deep blue left accent border
  doc.setFillColor(15, 23, 42);
  doc.rect(15, rowY, 1.2, aiSectionHeight, 'F');

  // Section Header Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(15, 23, 42);
  doc.text('AI LOADING EXPERT ANALYSIS (MK ADVISOR TECHNICAL AUDIT REPORT)', 18, rowY + 5);

  doc.setFillColor(249, 115, 22); // orange
  doc.rect(18, rowY + 6.2, 12, 0.4, 'F');

  // Render Bullets
  let currentBulletY = rowY + bulletStartYOffset;
  const bulletXKeys = 18;
  const bulletXValues = 62;

  wrappedBullets.forEach(wb => {
    // Print Key
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(6);
    doc.setTextColor(15, 23, 42);
    doc.text(wb.key, bulletXKeys, currentBulletY);

    // Print wrapped Value
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);
    doc.text(wb.wrapped, bulletXValues, currentBulletY);

    // Advance Y coordinates for the next bullet
    currentBulletY += wb.height + colGapSpacing;
  });
}
