import { TransformerItem } from '../types';

export const initialSampleItems: TransformerItem[] = [
  {
    id: 'item-1',
    projectCode: 'PT0512/1',
    componentName: 'Main Transformer Tank',
    length: 7800,
    width: 2800,
    height: 3800,
    weight: 42000,
    origin: 'India',
    stackable: false,
  },
  {
    id: 'item-rollers-1',
    projectCode: 'PT0512/1',
    componentName: 'Transformer Rollers',
    length: 1800,
    width: 900,
    height: 750,
    weight: 1400,
    origin: 'India',
    stackable: false,
  },
  {
    id: 'item-2',
    projectCode: 'PT0512/1',
    componentName: 'Main Conservator',
    length: 4600,
    width: 1600,
    height: 2200,
    weight: 2500,
    origin: 'India',
    stackable: false,
  },
  {
    id: 'item-3',
    projectCode: 'PT0512/1',
    componentName: 'Radiator Bank A',
    length: 3200,
    width: 1200,
    height: 2400,
    weight: 1800,
    origin: 'Oman',
    stackable: false,
  },
  {
    id: 'item-4',
    projectCode: 'PT0512/1',
    componentName: 'Radiator Bank B',
    length: 3200,
    width: 1200,
    height: 2400,
    weight: 1800,
    origin: 'Oman',
    stackable: false,
  },
  {
    id: 'item-5',
    projectCode: 'PT0512/1',
    componentName: 'HV Bushings Box',
    length: 2200,
    width: 950,
    height: 1100,
    weight: 1400,
    origin: 'Germany',
    stackable: true,
  },
  {
    id: 'item-6',
    projectCode: 'PT0512/1',
    componentName: 'LV Bushings Box',
    length: 1800,
    width: 900,
    height: 1000,
    weight: 950,
    origin: 'Germany',
    stackable: true,
  },
  {
    id: 'item-7',
    projectCode: 'PT0512/1',
    componentName: 'Marshalling Kiosk',
    length: 1200,
    width: 800,
    height: 1800,
    weight: 600,
    origin: 'Oman',
    stackable: false,
  },
  {
    id: 'item-8',
    projectCode: 'PT0512/1',
    componentName: 'Cable Connection Chamber',
    length: 2100,
    width: 1300,
    height: 1500,
    weight: 1100,
    origin: 'Oman',
    stackable: true,
  },
  {
    id: 'item-9',
    projectCode: 'PT0512/1',
    componentName: 'N2 Injection Fire System',
    length: 1600,
    width: 1100,
    height: 2000,
    weight: 1250,
    origin: 'India',
    stackable: false,
  },
  {
    id: 'item-10',
    projectCode: 'PT0512/1',
    componentName: 'OLTC Conservator',
    length: 2400,
    width: 1200,
    height: 1400,
    weight: 1150,
    origin: 'India',
    stackable: false,
  },
  {
    id: 'item-11',
    projectCode: 'PT0512/1',
    componentName: 'Control Panel Unit',
    length: 1400,
    width: 900,
    height: 2100,
    weight: 850,
    origin: 'Oman',
    stackable: false,
  },
  {
    id: 'item-12',
    projectCode: 'PT0512/1',
    componentName: 'Off-Circuit Tap Changer Assembly',
    length: 1900,
    width: 1000,
    height: 1200,
    weight: 750,
    origin: 'Oman',
    stackable: true,
  }
];
